<DrawingSpace>:
    on_press: self.cycle_colors()
    current_color: self.current_color

    canvas:
        Color:
            rgba: 0, 0, 0, .3
        Rectangle:
            pos: self.x + 10, self.y + 2
            size: self.width*0.05 + 4, self.height - 2

        Color:
            rgba: root.current_color

        Rectangle:
            pos: self.x + 12, self.y + 1
            size: self.width*0.05, self.height


